apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-disk-form
  labels:
    pv-name: gke-disk-form
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-disk-form
    fsType: ext4